### PR TITLE
Form improvements

### PR DESCRIPTION
**Pull request by AllanPooley**
Hey guys, just pushing through some code enhancements I seem to do in almost all my builds. Here's the list:

- Better loading logic (use Loading component, show when form is submitting)
- Don't show form fields once form has been submitted (just confirmation message)
- Base forms styles imported at <GravityForm /> component (app/components/GravityForm/Form.scss)
- Basic validation styling
- Basic error message styling
- Basic confirmation message styling
- GravityForms HTML field support
- Aussie phone validation

### CODE REVIEW

**Comment by AllanPooley** [comment]
Unfortunately I didn't use a branch for my other PR "Fix sanitizeJSON" so it's tagged along in this one. Can be removed here if required.

**Comment by falconmick** [comment]
For SOVA I added field level validation. Should I merge this into this PR or keep this PR more simple. It almost completely replaces validation.js

**Comment by AllanPooley** [comment]
That's definitely a need

> For SOVA I added field level validation. Should I merge this into this PR or keep this PR more simple. It almost completely replaces validation.js

That definitely sounds desirable, field level validation is something we've needed for a while. You're right, maybe keep this one simple, and once (if) we merge make a new PR on top of these changes?

**Comment by AllanPooley** [comment]
@samlogan fixed!

**Comment by AllanPooley** [comment]
Implemented suggested improvements @samlogan 

- Better out of the box spinner
- Removed aussie phone validation
- Loader inside the button while form is submitting

**Pull request merged**
