### PR TITLE
ACF components shielded with error boundaries

### PR DESCRIPTION
**Pull request by AllanPooley**
React 16 Error Boundaries (https://reactjs.org/docs/error-boundaries.html).

Applied to ensure our ACF components fail gracefully, rather than completely crashing the app. In the case of an error in an ACF component, it will be caught, logged, and a substitute component (`<ErrorBlock />`) will be rendered.

Example below

image

Introduces reusable, wrapping `<ErrorBoundary />` component:

```
export default class ErrorBoundary extends Component {
  state = {
    hasError: false
  };
  componentDidCatch(error, info) {
    this.setState({ hasError: true });
    console.error({error, info}); // redundant?
  }
  render() {
    const { hasError } = this.state;
    const errorMessage = 'Whoops, look like something went wrong here!';
    if (hasError) return <ErrorBlock errorMessage={errorMessage} />;
    return this.props.children;
  }
}
```

And `<ErrorBlock />` (isolated for CSS modules)

```
export const ErrorBlock = (props) => {
  const { errorMessage } = props;
  return (
    <div className="error-block">
      <p className="error-message">
        {errorMessage}
      </p>
    </div>
  );
};
```

### CODE REVIEW

**Comment by falconmick** [comment]
Maybe another good default addition would be a button to try again

**Comment by falconmick** [comment]
Also if the plan is to wrap this around ACF components, we could just put this around what we render in the https://github.com/distilagency/starward/blob/master/app/components/Page/PageContent.jsx#11

**Comment by falconmick** [comment]
```
const AcfComponent = ({ item, location }) => {
  const ComponentName = Layout[item.acf_fc_layout];
  return (
    <ErrorBoundary>
	    <ComponentName
	      location={location}
	      {...item}
    </ErrorBoundary>
    />
  );
};
```

**Comment by AllanPooley** [comment]
> Also if the plan is to wrap this around ACF components, we could just put this around what we render in the https://github.com/distilagency/starward/blob/master/app/components/Page/PageContent.jsx#11

That's where it is pal!

```
import React from 'react';
import * as Layout from '../Acf/Layout/';
// The rest ...
import ErrorBoundary from '../Common/ErrorBoundary';

const AcfComponent = ({ item, location }) => {
  const ComponentName = Layout[item.acf_fc_layout];
  return (
    <ErrorBoundary>
      <ComponentName
        location={location}
        {...item}
      />
    </ErrorBoundary>
  );
};

export const PageContent = (props) => {
  // The rest ...
}

```

**Comment by falconmick** [comment]
:| thats right file browsing on master probably isn't the best solution...

**Comment by AllanPooley** [comment]
@samlogan these are all excellent suggestions

**Comment by AllanPooley** [comment]
@samlogan will these commits do the trick?

**Pull request merged**
