### PR TITLE
Illegal character Regex updated

### PR DESCRIPTION
**Pull request by samlogan**
@chungeric and @markmollart have recently encountered issues with illegal characters from the WP WYSIWYG editor crashing the Starward API.

I have updated the Regex but it is hard to test without any offending copy to hand. Anyone have any recommendations, is the commit code better than the previous approach, it was ripped from [here](https://stackoverflow.com/questions/4374822/remove-all-special-characters-with-regexp) and [here](https://stackoverflow.com/questions/4374822/remove-all-special-characters-with-regexp).

Is anyone able to test with a recent offender from Sketch or similar?

### CODE REVIEW

**Comment by falconmick** [comment]
@samlogan the issue with this regex is that it will strip way too much.. in this example you can see that it strips punctuation. It will also strip things like ä which depending on the website could be important. See the following example using this regex: https://regexr.com/3u9o3

What we need to do is generate a fully comprehensive list of characters we want to support and then swap out our methodology to be a whitelist instead of blacklist

**Comment by samlogan** [comment]
@falconmick I have updated the Regex to `[^a-z0-9\\[\\]]` do you feel that is still too over-reaching? Agreed with you about the whitelist, any idea where we can generate that list of characters?

**Comment by falconmick** [comment]
`[^a-z0-9\\[\\]]` won't work as it will not match anything given that it boils down to two parts. part 1: match any non a-z 0-9 \ [ \ followed by a ]

You can see this by placing this inside of the regex tester &]

When building regex using the site I showed you before you can mouse over the regex string and it explains what it does + the screen down the bottom chunks your regex up making it more human readable: 

image

I have found the following regex: `[^\x00-\x7F]` of which I found from the following articles:
https://forums.asp.net/t/2104847.aspx?RegEx+to+remove+unicode+characters+
https://stackoverflow.com/questions/20856197/remove-non-ascii-character-in-string

you can see it working here: https://regexr.com/3u9o3

thoughts?

**Comment by falconmick** [comment]
My only concern with the above regex is that I am not an expert in ASCI so I don't know if this is taking too much out. for example it will remove things like `ä` which could be perfectly valid for your site.. in that case the people working on that site would need to know this and add it back. Maybe sombody can find out what the code range is for characters like that and exempt it

**Comment by falconmick** [comment]
Even better would be if we knew the character range that caused the issue and just blacklisted the entire range

**Comment by AllanPooley** [comment]
Do we have any logs or example characters from this issue @markmollart @chungeric, or does it simply cease to work? I'm with @falconmick on this one, I'd prefer to blacklist what we don't want, rather than whitelist a range of characters _we think_ clients will need.

As Andre 3000 once said:
🎶
> You can plan a pretty picnic
> But you can't predict the weather, Ms. Jackson
🎶

**Comment by AllanPooley** [comment]
@samlogan I image a strong html sanitising library might do away with this issue? Additionally, might save us some sweat cleaning up messy client pasted wysiwyg content, and possibility safe-guard against dangerous html injection?

https://www.npmjs.com/package/sanitize-html

**Comment by chungeric** [comment]
@samlogan I ran the deploy script on the Starward staging server the other day and had to restart pm2 to get the site to load properly again. Maybe it's an issue with the deploy script? Not sure. But running the deploy script without any git changes did not seem to break the site.

I'll keep an eye out to see what happens next time I deploy changes.

**Pull request closed without merging**
